version: '3.8'

services:
  reverse-proxy:
    build: 
      context: ./reverse-proxy
    ports:
      - "80:4000"

  frontend:
    build: 
      context: ./frontend
    volumes: 
      - ./frontend/html:/usr/share/nginx/html
  
  backend:
    build:
      context: ./backend